version: '2'
services:
  search:
    build: ./search
    volumes:
      - ./search/src:/var/www/search
      - ./search/docker-nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"   # Dist
      - "8001:8001" # Dev
    depends_on:
      - api
  app:
    build: ./app
    command: npm start
    volumes:
      - ./app/src:/var/www/app
    ports:
      - "8002:8002"
    depends_on:
      - api
      - api_user
  api:
    build: ./api
    # command: echo | pwd
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./api/src:/var/www/api
    env_file:
      - './api/.env'
    ports:
      - "3000:3000"
    depends_on:
      - db
  api_user:
    build: ./api_user
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./api_user/src:/var/www/api
    env_file:
      - './api_user/.env'
    ports:
      - "3001:3000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgres/data

volumes:
  pgdata:
