version: '2'
services:
  api:
    build: ./api
    # command: echo | pwd
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./api/src:/var/www/api
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgres/data

volumes:
  pgdata:
